
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

dist: jammy

language: python

cache: pip

python:
  - "3.10"

# command to install dependencies
install:
  - pip install .
  - pip install .[test]


# command to run tests
script:
  - pip install buildlackey
  - unittests
