"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['peskytm/peskytm.py']
OPTIONS = {}

setup(
    name='peskytm',
    version='0.1.0',
    app=APP,
    packages=['peskytm'],
    include_package_data=True,
    zip_safe=False,

    url='https://github.com/hasii2011/peskytm',
    author='Humberto A. Sanchez II',
    author_email='Humberto.A.Sanchez.II@gmail.com',
    description='Unmount pesky Time Machine Volumes',
    options={},
    setup_requires=['py2app'],
    install_requires=['click', '', '']
)
